// <auto-generated />
using System;
using Home.Contex;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Home.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Home.Models.EntertainmentsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("encategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("encomment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("endate")
                        .HasColumnType("date");

                    b.Property<string>("enname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("enplace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("enprice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Entertainments");
                });

            modelBuilder.Entity("Home.Models.FoodsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("foodCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("foodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("foodcomment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("fooddate")
                        .HasColumnType("date");

                    b.Property<string>("foodprice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Home.Models.InternetsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("incategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("incomment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("indate")
                        .HasColumnType("date");

                    b.Property<string>("inname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("inpcodenum")
                        .HasColumnType("integer");

                    b.Property<string>("inprice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Internets");
                });

            modelBuilder.Entity("Home.Models.MobilesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("mobcategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mobcomment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("mobdate")
                        .HasColumnType("date");

                    b.Property<string>("mobname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("mobnumber")
                        .HasColumnType("integer");

                    b.Property<string>("mobprice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mobiles");
                });

            modelBuilder.Entity("Home.Models.TransportsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("trcategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("trcomment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("trdate")
                        .HasColumnType("date");

                    b.Property<string>("trname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("trprice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Transports");
                });
#pragma warning restore 612, 618
        }
    }
}
